# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Animals' do
  use_frameworks!
  
  pod 'SnapKit'

  target 'AnimalsTests' do
    inherit! :search_paths
  end
end
